# /tutorial_template/jaffle_shop/models/sources.yml

version: 2

sources:
  - name: origin
    tables:
      - name: raw_county_cases_confirmed
      - name: raw_county_cases_probable
      - name: raw_county_deaths
      - name: county_names
      - name: county_populations